-- ═══════════════════════════════════════════════════════════════════════════
-- Fichas técnicas dos 23 pratos que não tinham nenhuma.
-- Rita Falcão, Chef Executiva · 16/08/2026
--
-- NÃO substitui o 2026-08-16-fichas-tecnicas-doses-corrigidas.sql, que corrige
-- as doses dos petiscos que JÁ têm ficha. São ficheiros complementares.
--
-- PARTE 1 cria os 18 itens de stock em falta. Os custos são ESTIMATIVAS minhas
--         de cash & carry — rever em Admin → Stock com os preços reais da Makro
--         antes de confiar no food cost que o painel de Rentabilidade mostrar.
-- PARTE 2 insere as fichas técnicas (product_id × stock_item_id × quantidade).
--
-- Quantidades POR DOSE SERVIDA, na unidade do item de stock.
-- Arroz e feijão estão em PESO SECO — é assim que se compram.
--
-- ATENÇÃO: alguns destes pratos podem ainda não existir na tabela products
-- (os 15 PF individuais, por exemplo). O insert ignora silenciosamente o que
-- não encontrar — correr a query de conferência no fim para ver o que faltou.
-- Idempotente. Reversão no fim do ficheiro.
-- ═══════════════════════════════════════════════════════════════════════════

begin;

-- ── PARTE 1) Itens de stock em falta ──────────────────────────────────────
insert into public.stock_items (nome, categoria, unidade, custo, quantidade, ativo)
select v.nome, v.categoria, v.unidade, v.custo, 0, true
from (values
  ('Piano de porco (entrecosto)', 'Carnes e Peixe', 'kg', 5.50),
  ('Maminha de vaca', 'Carnes e Peixe', 'kg', 15.50),
  ('Frango inteiro', 'Carnes e Peixe', 'kg', 3.20),
  ('Frango em pedaços (coxa e perna)', 'Carnes e Peixe', 'kg', 3.80),
  ('Carne de vaca para estufar (chã de fora)', 'Carnes e Peixe', 'kg', 9.50),
  ('Bacalhau em lascas demolhado', 'Carnes e Peixe', 'kg', 14.00),
  ('Filete de pescada congelado', 'Carnes e Peixe', 'kg', 6.80),
  ('Perca (filete congelado)', 'Carnes e Peixe', 'kg', 8.50),
  ('Ameijoa congelada', 'Carnes e Peixe', 'kg', 7.50),
  ('Massa cotovelo / macarrão', 'Mercearia', 'kg', 1.20),
  ('Pão ralado', 'Mercearia', 'kg', 1.80),
  ('Carnes de feijoada (orelha, chispe, farinheira)', 'Charcutaria', 'kg', 4.50),
  ('Couve portuguesa', 'Legumes', 'kg', 1.80),
  ('Azeitonas', 'Mercearia', 'kg', 5.00),
  ('Tremoços', 'Mercearia', 'kg', 2.80),
  ('Bolo da Dona Célia (fatia)', 'Semi-prontos', 'unidade', 0.70),
  ('Massa de pimentão', 'Mercearia', 'kg', 6.00),
  ('Orégãos', 'Mercearia', 'kg', 14.00)
) as v(nome, categoria, unidade, custo)
where not exists (select 1 from public.stock_items s where s.nome = v.nome);

-- ── PARTE 2) Fichas técnicas ──────────────────────────────────────────────
insert into public.stock_receitas (product_id, stock_item_id, quantidade)
select p.id, s.id, v.qtd::numeric
from (values
  ('Bife Acebolado', 'Bife de vaca (acém/vazia)', 0.18),
  ('Bife Acebolado', 'Cebola', 0.5),
  ('Bife Acebolado', 'Azeite virgem extra', 0.005),
  ('Bife Acebolado', 'Arroz agulha', 0.05),
  ('Bife Acebolado', 'Feijão preto', 0.048),
  ('Bife Acebolado', 'Farinha de mandioca (farofa)', 0.022),
  ('Bife Acebolado', 'Manteiga', 0.17),
  ('Bife Acebolado', 'Alface / mistura de salada', 0.04),
  ('Bife Acebolado', 'Tomate fresco', 0.015),
  ('Bife Acebolado', 'Cebola', 0.1),
  ('Bife Acebolado', 'Alho fresco', 0.002),
  ('Bife Acebolado', 'Azeite virgem extra', 0.02),
  ('Bife Acebolado', 'Especiarias base (louro, alho em pó, pimenta preta, sal)', 0.001),
  ('Peito de Frango Grelhado', 'Peito de frango', 0.2),
  ('Peito de Frango Grelhado', 'Limão', 0.02),
  ('Peito de Frango Grelhado', 'Coentros', 0.1),
  ('Peito de Frango Grelhado', 'Azeite virgem extra', 0.005),
  ('Peito de Frango Grelhado', 'Arroz agulha', 0.05),
  ('Peito de Frango Grelhado', 'Feijão preto', 0.048),
  ('Peito de Frango Grelhado', 'Farinha de mandioca (farofa)', 0.022),
  ('Peito de Frango Grelhado', 'Manteiga', 0.17),
  ('Peito de Frango Grelhado', 'Alface / mistura de salada', 0.04),
  ('Peito de Frango Grelhado', 'Tomate fresco', 0.015),
  ('Peito de Frango Grelhado', 'Cebola', 0.1),
  ('Peito de Frango Grelhado', 'Alho fresco', 0.002),
  ('Peito de Frango Grelhado', 'Azeite virgem extra', 0.02),
  ('Peito de Frango Grelhado', 'Especiarias base (louro, alho em pó, pimenta preta, sal)', 0.001),
  ('Bacalhau à Brás', 'Bacalhau desfiado demolhado congelado', 0.16),
  ('Bacalhau à Brás', 'Batata palha', 0.08),
  ('Bacalhau à Brás', 'Ovos', 2.0),
  ('Bacalhau à Brás', 'Cebola', 0.5),
  ('Bacalhau à Brás', 'Azeitonas', 0.015),
  ('Bacalhau à Brás', 'Azeite virgem extra', 0.008),
  ('Bacalhau à Brás', 'Alface / mistura de salada', 0.04),
  ('Bacalhau à Brás', 'Tomate fresco', 0.015),
  ('Bacalhau à Brás', 'Azeite virgem extra', 0.008),
  ('Bacalhau à Brás', 'Especiarias base (louro, alho em pó, pimenta preta, sal)', 0.0005),
  ('Filet de Peixe', 'Filete de pescada congelado', 0.2),
  ('Filet de Peixe', 'Farinha de trigo', 0.02),
  ('Filet de Peixe', 'Ovos', 1.0),
  ('Filet de Peixe', 'Limão', 0.015),
  ('Filet de Peixe', 'Óleo de fritura (girassol)', 0.015),
  ('Filet de Peixe', 'Arroz agulha', 0.05),
  ('Filet de Peixe', 'Feijão preto', 0.048),
  ('Filet de Peixe', 'Farinha de mandioca (farofa)', 0.022),
  ('Filet de Peixe', 'Manteiga', 0.17),
  ('Filet de Peixe', 'Alface / mistura de salada', 0.04),
  ('Filet de Peixe', 'Tomate fresco', 0.015),
  ('Filet de Peixe', 'Cebola', 0.1),
  ('Filet de Peixe', 'Alho fresco', 0.002),
  ('Filet de Peixe', 'Azeite virgem extra', 0.02),
  ('Filet de Peixe', 'Especiarias base (louro, alho em pó, pimenta preta, sal)', 0.001),
  ('Peito de Frango Amilanesa', 'Peito de frango', 0.2),
  ('Peito de Frango Amilanesa', 'Ovos', 1.0),
  ('Peito de Frango Amilanesa', 'Farinha de trigo', 0.025),
  ('Peito de Frango Amilanesa', 'Pão ralado', 0.04),
  ('Peito de Frango Amilanesa', 'Óleo de fritura (girassol)', 0.02),
  ('Peito de Frango Amilanesa', 'Limão', 0.015),
  ('Peito de Frango Amilanesa', 'Arroz agulha', 0.05),
  ('Peito de Frango Amilanesa', 'Feijão preto', 0.048),
  ('Peito de Frango Amilanesa', 'Farinha de mandioca (farofa)', 0.022),
  ('Peito de Frango Amilanesa', 'Manteiga', 0.17),
  ('Peito de Frango Amilanesa', 'Alface / mistura de salada', 0.04),
  ('Peito de Frango Amilanesa', 'Tomate fresco', 0.015),
  ('Peito de Frango Amilanesa', 'Cebola', 0.1),
  ('Peito de Frango Amilanesa', 'Alho fresco', 0.002),
  ('Peito de Frango Amilanesa', 'Azeite virgem extra', 0.02),
  ('Peito de Frango Amilanesa', 'Especiarias base (louro, alho em pó, pimenta preta, sal)', 0.001),
  ('Carne de Porco à Alentejana', 'Entremeada de porco', 0.18),
  ('Carne de Porco à Alentejana', 'Ameijoa congelada', 0.12),
  ('Carne de Porco à Alentejana', 'Batata', 0.15),
  ('Carne de Porco à Alentejana', 'Massa de pimentão', 0.008),
  ('Carne de Porco à Alentejana', 'Vinho branco de cozinha', 0.04),
  ('Carne de Porco à Alentejana', 'Alho fresco', 0.005),
  ('Carne de Porco à Alentejana', 'Coentros', 0.1),
  ('Carne de Porco à Alentejana', 'Óleo de fritura (girassol)', 0.015),
  ('Carne de Porco à Alentejana', 'Azeite virgem extra', 0.005),
  ('Carne de Porco à Alentejana', 'Alface / mistura de salada', 0.04),
  ('Carne de Porco à Alentejana', 'Tomate fresco', 0.015),
  ('Carne de Porco à Alentejana', 'Azeite virgem extra', 0.008),
  ('Carne de Porco à Alentejana', 'Especiarias base (louro, alho em pó, pimenta preta, sal)', 0.0005),
  ('Bacalhau a Gomes Sá', 'Bacalhau em lascas demolhado', 0.16),
  ('Bacalhau a Gomes Sá', 'Batata', 0.2),
  ('Bacalhau a Gomes Sá', 'Ovos', 1.0),
  ('Bacalhau a Gomes Sá', 'Cebola', 1.0),
  ('Bacalhau a Gomes Sá', 'Azeitonas', 0.02),
  ('Bacalhau a Gomes Sá', 'Alho fresco', 0.004),
  ('Bacalhau a Gomes Sá', 'Azeite virgem extra', 0.02),
  ('Bacalhau a Gomes Sá', 'Alface / mistura de salada', 0.04),
  ('Bacalhau a Gomes Sá', 'Tomate fresco', 0.015),
  ('Bacalhau a Gomes Sá', 'Azeite virgem extra', 0.008),
  ('Bacalhau a Gomes Sá', 'Especiarias base (louro, alho em pó, pimenta preta, sal)', 0.0005),
  ('Frango Assado', 'Frango inteiro', 0.35),
  ('Frango Assado', 'Colorau', 0.003),
  ('Frango Assado', 'Alho fresco', 0.003),
  ('Frango Assado', 'Azeite virgem extra', 0.008),
  ('Frango Assado', 'Arroz agulha', 0.05),
  ('Frango Assado', 'Feijão preto', 0.048),
  ('Frango Assado', 'Farinha de mandioca (farofa)', 0.022),
  ('Frango Assado', 'Manteiga', 0.17),
  ('Frango Assado', 'Alface / mistura de salada', 0.04),
  ('Frango Assado', 'Tomate fresco', 0.015),
  ('Frango Assado', 'Cebola', 0.1),
  ('Frango Assado', 'Alho fresco', 0.002),
  ('Frango Assado', 'Azeite virgem extra', 0.02),
  ('Frango Assado', 'Especiarias base (louro, alho em pó, pimenta preta, sal)', 0.001),
  ('Maminha na Chapa', 'Maminha de vaca', 0.2),
  ('Maminha na Chapa', 'Azeite virgem extra', 0.005),
  ('Maminha na Chapa', 'Especiarias base (louro, alho em pó, pimenta preta, sal)', 0.001),
  ('Maminha na Chapa', 'Arroz agulha', 0.05),
  ('Maminha na Chapa', 'Feijão preto', 0.048),
  ('Maminha na Chapa', 'Farinha de mandioca (farofa)', 0.022),
  ('Maminha na Chapa', 'Manteiga', 0.17),
  ('Maminha na Chapa', 'Alface / mistura de salada', 0.04),
  ('Maminha na Chapa', 'Tomate fresco', 0.015),
  ('Maminha na Chapa', 'Cebola', 0.1),
  ('Maminha na Chapa', 'Alho fresco', 0.002),
  ('Maminha na Chapa', 'Azeite virgem extra', 0.02),
  ('Maminha na Chapa', 'Especiarias base (louro, alho em pó, pimenta preta, sal)', 0.001),
  ('Bacalhau com Natas', 'Bacalhau desfiado demolhado congelado', 0.15),
  ('Bacalhau com Natas', 'Batata', 0.2),
  ('Bacalhau com Natas', 'Natas', 0.1),
  ('Bacalhau com Natas', 'Leite', 0.05),
  ('Bacalhau com Natas', 'Farinha de trigo', 0.015),
  ('Bacalhau com Natas', 'Manteiga', 0.2),
  ('Bacalhau com Natas', 'Cebola', 0.5),
  ('Bacalhau com Natas', 'Queijo', 1.0),
  ('Bacalhau com Natas', 'Óleo de fritura (girassol)', 0.015),
  ('Bacalhau com Natas', 'Alface / mistura de salada', 0.04),
  ('Bacalhau com Natas', 'Tomate fresco', 0.015),
  ('Bacalhau com Natas', 'Azeite virgem extra', 0.008),
  ('Bacalhau com Natas', 'Especiarias base (louro, alho em pó, pimenta preta, sal)', 0.0005),
  ('Carne de Panela', 'Carne de vaca para estufar (chã de fora)', 0.2),
  ('Carne de Panela', 'Cebola', 1.0),
  ('Carne de Panela', 'Tomate pelado', 0.08),
  ('Carne de Panela', 'Vinho branco de cozinha', 0.04),
  ('Carne de Panela', 'Alho fresco', 0.004),
  ('Carne de Panela', 'Azeite virgem extra', 0.008),
  ('Carne de Panela', 'Arroz agulha', 0.05),
  ('Carne de Panela', 'Feijão preto', 0.048),
  ('Carne de Panela', 'Farinha de mandioca (farofa)', 0.022),
  ('Carne de Panela', 'Manteiga', 0.17),
  ('Carne de Panela', 'Alface / mistura de salada', 0.04),
  ('Carne de Panela', 'Tomate fresco', 0.015),
  ('Carne de Panela', 'Cebola', 0.1),
  ('Carne de Panela', 'Alho fresco', 0.002),
  ('Carne de Panela', 'Azeite virgem extra', 0.02),
  ('Carne de Panela', 'Especiarias base (louro, alho em pó, pimenta preta, sal)', 0.001),
  ('Piano', 'Piano de porco (entrecosto)', 0.35),
  ('Piano', 'Colorau', 0.004),
  ('Piano', 'Alho fresco', 0.004),
  ('Piano', 'Azeite virgem extra', 0.008),
  ('Piano', 'Arroz agulha', 0.05),
  ('Piano', 'Feijão preto', 0.048),
  ('Piano', 'Farinha de mandioca (farofa)', 0.022),
  ('Piano', 'Manteiga', 0.17),
  ('Piano', 'Alface / mistura de salada', 0.04),
  ('Piano', 'Tomate fresco', 0.015),
  ('Piano', 'Cebola', 0.1),
  ('Piano', 'Alho fresco', 0.002),
  ('Piano', 'Azeite virgem extra', 0.02),
  ('Piano', 'Especiarias base (louro, alho em pó, pimenta preta, sal)', 0.001),
  ('Massada de Perca', 'Perca (filete congelado)', 0.18),
  ('Massada de Perca', 'Massa cotovelo / macarrão', 0.08),
  ('Massada de Perca', 'Tomate pelado', 0.1),
  ('Massada de Perca', 'Cebola', 0.5),
  ('Massada de Perca', 'Alho fresco', 0.004),
  ('Massada de Perca', 'Coentros', 0.1),
  ('Massada de Perca', 'Azeite virgem extra', 0.01),
  ('Massada de Perca', 'Alface / mistura de salada', 0.04),
  ('Massada de Perca', 'Tomate fresco', 0.015),
  ('Massada de Perca', 'Azeite virgem extra', 0.008),
  ('Massada de Perca', 'Especiarias base (louro, alho em pó, pimenta preta, sal)', 0.0005),
  ('Feijoada da Casa', 'Feijão preto', 0.12),
  ('Feijoada da Casa', 'Entremeada de porco', 0.08),
  ('Feijoada da Casa', 'Chouriço de carne', 0.04),
  ('Feijoada da Casa', 'Paio', 0.03),
  ('Feijoada da Casa', 'Carnes de feijoada (orelha, chispe, farinheira)', 0.08),
  ('Feijoada da Casa', 'Arroz agulha', 0.05),
  ('Feijoada da Casa', 'Farinha de mandioca (farofa)', 0.022),
  ('Feijoada da Casa', 'Manteiga', 0.17),
  ('Feijoada da Casa', 'Couve portuguesa', 0.06),
  ('Feijoada da Casa', 'Laranja', 0.25),
  ('Feijoada da Casa', 'Cebola', 0.05),
  ('Feijoada da Casa', 'Alho fresco', 0.001),
  ('Feijoada da Casa', 'Azeite virgem extra', 0.008),
  ('Feijoada da Casa', 'Especiarias base (louro, alho em pó, pimenta preta, sal)', 0.001),
  ('Frango Ensopado', 'Frango em pedaços (coxa e perna)', 0.28),
  ('Frango Ensopado', 'Pão para Pica-Pau / acompanhamento', 1.0),
  ('Frango Ensopado', 'Cebola', 0.5),
  ('Frango Ensopado', 'Tomate pelado', 0.06),
  ('Frango Ensopado', 'Alho fresco', 0.004),
  ('Frango Ensopado', 'Coentros', 0.1),
  ('Frango Ensopado', 'Azeite virgem extra', 0.01),
  ('Frango Ensopado', 'Arroz agulha', 0.05),
  ('Frango Ensopado', 'Feijão preto', 0.048),
  ('Frango Ensopado', 'Farinha de mandioca (farofa)', 0.022),
  ('Frango Ensopado', 'Manteiga', 0.17),
  ('Frango Ensopado', 'Alface / mistura de salada', 0.04),
  ('Frango Ensopado', 'Tomate fresco', 0.015),
  ('Frango Ensopado', 'Cebola', 0.1),
  ('Frango Ensopado', 'Alho fresco', 0.002),
  ('Frango Ensopado', 'Azeite virgem extra', 0.02),
  ('Frango Ensopado', 'Especiarias base (louro, alho em pó, pimenta preta, sal)', 0.001),
  ('Bitoque da Casa', 'Bife de vaca (acém/vazia)', 0.18),
  ('Bitoque da Casa', 'Ovos', 1.0),
  ('Bitoque da Casa', 'Batata', 0.2),
  ('Bitoque da Casa', 'Óleo de fritura (girassol)', 0.01),
  ('Bitoque da Casa', 'Arroz agulha', 0.05),
  ('Bitoque da Casa', 'Manteiga', 0.25),
  ('Bitoque da Casa', 'Alho fresco', 0.002),
  ('Bitoque da Casa', 'Vinho branco de cozinha', 0.04),
  ('Bitoque da Casa', 'Mostarda', 0.01),
  ('Bitoque da Casa', 'Azeite virgem extra', 0.005),
  ('Bitoque da Casa', 'Guaraná Antarctica 33 cl', 1.0),
  ('Bitoque da Casa', 'Café moído', 1.0),
  ('Pica-Pau', 'Lombo de porco (Pica-Pau)', 0.16),
  ('Pica-Pau', 'Alho fresco', 0.008),
  ('Pica-Pau', 'Vinho branco de cozinha', 0.05),
  ('Pica-Pau', 'Mostarda', 0.012),
  ('Pica-Pau', 'Pepino de conserva', 0.04),
  ('Pica-Pau', 'Manteiga', 0.15),
  ('Pica-Pau', 'Azeite virgem extra', 0.008),
  ('Pica-Pau', 'Pão para Pica-Pau / acompanhamento', 1.0),
  ('Tábua da Casa', 'Queijo da Serra (meia cura)', 0.06),
  ('Tábua da Casa', 'Queijo de Azeitão', 0.06),
  ('Tábua da Casa', 'Presunto fatiado', 0.06),
  ('Tábua da Casa', 'Chouriço de carne', 0.05),
  ('Tábua da Casa', 'Paio', 0.05),
  ('Tábua da Casa', 'Marmelada', 0.04),
  ('Tábua da Casa', 'Pão para Pica-Pau / acompanhamento', 1.0),
  ('Azeitonas Temperadas', 'Azeitonas', 0.08),
  ('Azeitonas Temperadas', 'Alho fresco', 0.002),
  ('Azeitonas Temperadas', 'Orégãos', 0.001),
  ('Azeitonas Temperadas', 'Azeite virgem extra', 0.005),
  ('Tremoços', 'Tremoços', 0.1),
  ('Bolo da Dona Célia (fatia)', 'Bolo da Dona Célia (fatia)', 1.0),
  ('Heineken (imperial)', 'Barril Heineken 50L', 0.2),
  ('Copo Cheio (IPA da casa)', 'Cerveja da casa — IPA (Copo Cheio)', 0.33)
) as v(produto, ingrediente, qtd)
join public.products    p on p.nome = v.produto
join public.stock_items s on s.nome = v.ingrediente
where not exists (
  select 1 from public.stock_receitas x
  where x.product_id = p.id and x.stock_item_id = s.id
);

-- ── 3) Conferência: que pratos das fichas NÃO existem em products ─────────
select distinct v.produto as prato_em_falta_na_tabela_products
from (values
  ('Azeitonas Temperadas'),
  ('Bacalhau a Gomes Sá'),
  ('Bacalhau com Natas'),
  ('Bacalhau à Brás'),
  ('Bife Acebolado'),
  ('Bitoque da Casa'),
  ('Bolo da Dona Célia (fatia)'),
  ('Carne de Panela'),
  ('Carne de Porco à Alentejana'),
  ('Copo Cheio (IPA da casa)'),
  ('Feijoada da Casa'),
  ('Filet de Peixe'),
  ('Frango Assado'),
  ('Frango Ensopado'),
  ('Heineken (imperial)'),
  ('Maminha na Chapa'),
  ('Massada de Perca'),
  ('Peito de Frango Amilanesa'),
  ('Peito de Frango Grelhado'),
  ('Piano'),
  ('Pica-Pau'),
  ('Tremoços'),
  ('Tábua da Casa')
) as v(produto)
left join public.products p on p.nome = v.produto
where p.id is null
order by 1;

-- ── 4) Conferência: food cost resultante por prato ────────────────────────
select p.nome as prato,
       round(sum(r.quantidade * s.custo), 4) as custo_dose,
       p.preco as pvp_actual,
       round(sum(r.quantidade * s.custo) / nullif(p.preco,0) * 100, 1) as food_cost_pct,
       count(*) filter (where s.custo is null) as ingredientes_sem_custo
from public.stock_receitas r
join public.products    p on p.id = r.product_id
join public.stock_items s on s.id = r.stock_item_id
group by p.nome, p.preco
order by food_cost_pct desc nulls last;

commit;

-- ═══════════════════════════════════════════════════════════════════════════
-- REVERSÃO — apaga as fichas destes 23 pratos e os 18 itens criados
-- ═══════════════════════════════════════════════════════════════════════════
--
-- begin;
-- delete from public.stock_receitas r
-- using public.products p
-- where r.product_id = p.id and p.nome in (
--   'Azeitonas Temperadas',
--   'Bacalhau a Gomes Sá',
--   'Bacalhau com Natas',
--   'Bacalhau à Brás',
--   'Bife Acebolado',
--   'Bitoque da Casa',
--   'Bolo da Dona Célia (fatia)',
--   'Carne de Panela',
--   'Carne de Porco à Alentejana',
--   'Copo Cheio (IPA da casa)',
--   'Feijoada da Casa',
--   'Filet de Peixe',
--   'Frango Assado',
--   'Frango Ensopado',
--   'Heineken (imperial)',
--   'Maminha na Chapa',
--   'Massada de Perca',
--   'Peito de Frango Amilanesa',
--   'Peito de Frango Grelhado',
--   'Piano',
--   'Pica-Pau',
--   'Tremoços',
--   'Tábua da Casa'
-- );
-- delete from public.stock_items where nome in (
--   'Piano de porco (entrecosto)',
--   'Maminha de vaca',
--   'Frango inteiro',
--   'Frango em pedaços (coxa e perna)',
--   'Carne de vaca para estufar (chã de fora)',
--   'Bacalhau em lascas demolhado',
--   'Filete de pescada congelado',
--   'Perca (filete congelado)',
--   'Ameijoa congelada',
--   'Massa cotovelo / macarrão',
--   'Pão ralado',
--   'Carnes de feijoada (orelha, chispe, farinheira)',
--   'Couve portuguesa',
--   'Azeitonas',
--   'Tremoços',
--   'Bolo da Dona Célia (fatia)',
--   'Massa de pimentão',
--   'Orégãos'
-- );
-- commit;
